---
- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
    - name: Copy WAR file tomcat
      copy:
        src: "/var/snap/jenkins/4874/workspace/AnsiWebApp/target/AnsiWebApp.war"
        dest: "/opt/tomcat/webapps/AnsiWebApp.war"
        remote_src: no
     
    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
        
